### ISSUE TITLE
Use https://github.com/lancaster-university/codal-nrf52

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-robotis#14]
We do not want to have to maintain multiple version of a CODAL layer for NRF52. Please use https://github.com/lancaster-university/codal-nrf52

**Comment by OpusK** [comment]
Hi, @pelikhan.

I want it too and I'm doing PR to them.  However, in the development phase, we want to use a separate repository to immediately apply what we want to test.  Finally, we will change to Lancaster's.

**Comment by pelikhan** [comment]
Eventually...

**Comment by pelikhan** [comment]
My recommandation now is to keep using your fork of codal-nrf52 **and** port fixes/upgrade as Pull Requests in lancater/codal-nrf52.
Our USA and UK teams are impacted by COVID-19 so we can't really process them quickly.

**Comment by OpusK** [comment]
OK, I will replace it with Lancaster's one later.
