### ISSUE TITLE
"...more" category is not refreshed.

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#25]
I clicked "... more" of "PINS" category on local PC. 
But blocks are not refreshed like below.

Working fine on the website "maker.makecode.com".
Working fine on another local PC.

![image](https://user-images.githubusercontent.com/61178787/76583741-6ddedb00-651d-11ea-97cc-af1875499bfe.png)
![image](https://user-images.githubusercontent.com/61178787/76583769-7f27e780-651d-11ea-8f9a-1b928f22cac4.png)

**Comment by kigateG** [comment]
It's fine after re-installation of pxt.

**Comment by pelikhan** [comment]
We fixed a caching issue not so long ago.

**Comment by kigateG** [comment]
> We fixed a caching issue not so long ago.

thank you.
