### ISSUE TITLE
[Error] Cannot read property

### ISSUE THREAD

**Issue by OpusK** [microsoft/pxt-robotis#26]
@pelikhan,

The issue below (#23) has not been resolved.
And even though it is declared as below in shims.d.ts, it still shows 'of undefined', not 'of dynamixel' ...
Strangely, despite this error, the board works fine.

```
declare namespace dynamixel {
    /**
     * Opens a DYNAMIXEL communication driver
     */
    //% shim=dynamixel::internalCreateDXLDevice
    function internalCreateDXLDevice(tx: DigitalInOutPin, rx: DigitalInOutPin, dir: DigitalInOutPin, id: int32): DynamixelDevice;
}
```

![image](https://user-images.githubusercontent.com/18085958/76713259-a0c5e080-6762-11ea-9b4a-8067083b058e.png)

And, the below .png file is the example code with the above error.

![ROBOTIS-DYNAMIXEL-Velocity](https://user-images.githubusercontent.com/18085958/76713274-baffbe80-6762-11ea-8037-bfa28438f286.png)

---------------
_Originally posted by @OpusK in https://github.com/microsoft/pxt-robotis/pull/23_

> What you need to do is to implement a javascript version of the C++ call. 

I think I wrote a shim through the code above as per the manual.

> See serial shim: https://github.com/microsoft/pxt-common-packages/blob/76fe391800fd44825839573da32cdca3ca5076ed/libs/core/sim/serial.ts#L40

Your link is not a shim, but a sim file (for simulation). Isn't it right to refer to [shims.d.ts](https://github.com/microsoft/pxt-robotis/blob/master/libs/serial/shims.d.ts) for shim?
Of course, I haven't implemented simulation yet, so when implementing sim it's right to refer to the file you gave the link to.
I've also seen errors related to simulation, so I know I need to implement sim someday. However, the current error is about shim. 

I think it was implemented properly except for simulation, isn't it?
Like docs, should it be uploaded to the cloud to be recognized as a namespace called dynamixel, not undefined?
If so, please merge. I will implement the simulator later.

_Originally posted by @OpusK in https://github.com/microsoft/pxt-robotis/pull/23_

**Comment by pelikhan** [comment]
Peli will put the skeleton code to unblock you.

**Comment by pelikhan** [comment]
Sorry i haven't been looking at it yet.

**Comment by pelikhan** [comment]
Fixed, see dynamixel/sim/*.ts

**Comment by pelikhan** [comment]
You'll need to implement a "dynamixel" simulator in javascript.

**Comment by OpusK** [comment]
Thanks for your support :)
