### ISSUE TITLE
We need a way to communicate!

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-robotis#30]
My Korean is unfortunately non-existent. Are you ok doing some kind of online meeting in English every week to track progress?

**Comment by OpusK** [comment]
Hi, @pelikhan 

That's what we wanted!
We have too many questions. (Including your GitHub Repo workflow.)

It would be better to talk about the details(method, time, cycle, etc.) by e-mail.
We will send the mail ASAP.
