### ISSUE TITLE
[Workflow] GitHub workflow

### ISSUE THREAD

**Issue by OpusK** [microsoft/pxt-robotis#31]
Hi, @pelikhan.

Below is the question I asked about the GitHub workflow I asked you after you gave me write permission previously.

Can you explain how you would like to collaborate with us about the following?

----

Hi, @pelikhan 

During the development period, would you like to proceed with the way we merge PR when you approve it?
Or, would you only want to make a review if we requested it? (That is, if the PR does pass the CI if we did not request a review, are we merging without your review?)

Also, in the case of release, what do you want to do?

All of these questions are about the development stage.

_Originally posted by @OpusK in https://github.com/microsoft/pxt-robotis/pull/28#issuecomment-599867273_

**Comment by pelikhan** [comment]
Add me to all the reviews so I can eventually look at them - even when closed.

**Comment by OpusK** [comment]
What about Release?
Do you want to do this through PR as well?
Or, do you want to handle it like before?

**Comment by pelikhan** [comment]
You can bump do 

    pxt bump —update

**Comment by OpusK** [comment]
My question was about our authority over this repo.
Anyway, I understand that we have permission to bump and release. (We have written permission, but we understand that bumps and releases are the only ones you have permission by policy)
