### ISSUE TITLE
Extend resolution 320x240 for LCD screen x 8bit

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-robotis#32]
Extend screen driver

**Comment by pelikhan** [comment]
Arcade assumes that the screen is 160x120 4bit color. All our APIs for game creation also use that assumption. For larger screen, we simply upscale the resolution in the driver but the user does not see a larger resolution.

It would be possible to support a different resolution but it might make compability with arcade harder.

**Comment by pelikhan** [comment]
The decision is to resolution compatible with arcade - 160x120. Closing.

**Comment by ROBOTIS-Will** [comment]
Due to the limitation of Arcade, ROBOTIS will accept this resolution.
