### ISSUE TITLE
Modify Download Message...

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#34]
Hi.

Can I change download message UI like microbit?

![image](https://user-images.githubusercontent.com/61178787/77486710-c5613d00-6e73-11ea-9199-0831a69879a3.png)

->

![image](https://user-images.githubusercontent.com/61178787/77486785-f80b3580-6e73-11ea-8adc-3c5d92d6ae6e.png)

I tried with below codes to change body ("Move the ...") but not work.
https://github.com/microsoft/pxt-robotis/blob/4f62b68301184d21a0a410d9248ffbe863bfa052/editor/extension.ts#L59

And I tried with below. It works. Do I have to change pxt?
https://github.com/microsoft/pxt/blob/5531f0a3fe88242be6d4ce899c25ca3c61323ca6/webapp/src/cmds.ts#L82

thanks.

**Comment by pelikhan** [comment]
You can provide your own UI for the download dialog via the editor extensions. See the microsoft/pxt-microbit project for an example of such use.

https://github.com/microsoft/pxt-microbit/blob/master/editor/extension.tsx#L968

**Comment by pelikhan** [comment]
And enable this field in pxtarget.json

https://github.com/microsoft/pxt-microbit/blob/master/pxtarget.json#L296

**Comment by pelikhan** [comment]
Peli to add skeleton code.

**Comment by kigateG** [comment]
Maker and Robotis targets already use the filed and function like below.
Are there any settings I missed?

https://github.com/microsoft/pxt-robotis/blob/4f62b68301184d21a0a410d9248ffbe863bfa052/pxtarget.json#L246

https://github.com/microsoft/pxt-robotis/blob/4f62b68301184d21a0a410d9248ffbe863bfa052/editor/extension.ts#L7

**Comment by pelikhan** [comment]
You are right, we had a bug in pxt. You will need to integrate this commit

https://github.com/microsoft/pxt-maker/commit/d083bb864b8c05a89b9cf436213fdd26e397e9a9

and bump pxt to the latest to pick up the fixes.

**Comment by pelikhan** [comment]
Ping me if you need help integrating these changes.

**Comment by kigateG** [comment]
Hi,
I did...

delete extension.ts
add extension.tsx
modify tsconfig.json and package.json

then... 

npm install

Log has no error. But it still show the message box only...
![image](https://user-images.githubusercontent.com/61178787/78622305-c3f63280-78bf-11ea-9fa3-6402fe836a95.png)

**Comment by pelikhan** [comment]
I’ll do the patch.

________________________________

**Comment by pelikhan** [comment]
Fixed.

**Comment by kigateG** [comment]
Thank you pelikhan.
