### ISSUE TITLE
Display bread board

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#35]
Hi.

How does it work to display the bread board in simulator area.

for example...
The BB is displayed only when the block is connected in case of LCD extension.

![image](https://user-images.githubusercontent.com/61178787/77489828-9bf8df00-6e7c-11ea-8e57-0586b9d109dd.png)

But The BB is displayed by adding Game extension. (even though blocks are not connected.)

**Comment by pelikhan** [comment]
Could you share programs that reproduces both of the issues?

**Comment by pelikhan** [comment]
Repro: https://makecode.com/_7ioMg2b6Efka

**Comment by ROBOTIS-Will** [comment]
https://makecode.seeedstudio.com/#editor

**Comment by pelikhan** [comment]
I don’t think you want to use the breadboard so board.json is irrelevant to your editor. You need to design your simulator first.
