### ISSUE TITLE
Selection of extension exposure.

### ISSUE THREAD

**Issue by kjsii123** [microsoft/pxt-robotis#36]
How can I expose only the items I want when exposing extensions?

For example:
If you look at the capture below, libs / base, libs / core, etc. are included in the extension and exposed.
![extension_robotis](https://user-images.githubusercontent.com/12948544/77499299-12094000-6e95-11ea-82ed-eada9577d524.jpg)

However, as shown below, the extension is not exposed in the case of Lego. Which part should I change? Or is there a reference you can refer to?
![extension_lego](https://user-images.githubusercontent.com/12948544/77499301-133a6d00-6e95-11ea-9744-a4bff92c94f8.jpg)

**Comment by pelikhan** [comment]
You can set a flag

     "hidden": true

in pxt.json
