### ISSUE TITLE
When exposing categories, how can I expose only the items I want?

### ISSUE THREAD

**Issue by kjsii123** [microsoft/pxt-robotis#37]
For example
For categories, is it possible to selectively expose only the desired category, not all categories included in the "dependencies":{  } in the pxt.json file?

**Comment by pelikhan** [comment]
You can currently hide a category in pxttarget.json (see https://github.com/microsoft/pxt-arcade/blob/master/pxtarget.json#L281) and reenable from a pxt.json file (https://github.com/microsoft/pxt-arcade/blob/master/libs/edge-connector/pxt.json#L3)
