### ISSUE TITLE
Questions about making simulation

### ISSUE THREAD

**Issue by HgonKim** [microsoft/pxt-robotis#42]
Is it possible to make a triangle or star shaped buttons by modifying the data of "buttons" of board.json in Makecode?
![image](https://user-images.githubusercontent.com/30816300/79085622-3f4e5d00-7d74-11ea-962e-fe190c5148a5.png)

Or do I need to parse svg data like **lego** or **brainpad** way to create simulation ui like button, screen, motor etc.
![image](https://user-images.githubusercontent.com/30816300/79085677-715fbf00-7d74-11ea-915a-cb174ecff466.png)

Thanks.

**Comment by kigateG** [comment]
Done.
