### ISSUE TITLE
Display same blocks in different categories.

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#5]
I have "block_1", "block_2"
I want to display "block_1", "block_2" in "category_1" for "robot_1".
I want to display "block_1" in "category_1", "block_2" in "category_2" for "robot_2".

Is it possible to create common blocks and display them in different category of different robots?

Now I made the code as shown below.

Set "dependencies: file:../robot_1_blocks" for "robot_1".
Make a ".ts file" in "robot_1_blocks" and defile "namespace c1 {b1, b2}"

Set "dependencies: file:../robot_2_blocks" for "robot_2".
Make a ".ts file" in "robot_2_blocks" and defile "namespace c1 {b1}, namespace c2 {b2}"

Thank you.

**Comment by pelikhan** [comment]
could you write the i2c requirement here?
