### ISSUE TITLE
Hide some blocks in Loops, Logic category 

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#6]
HI,

How can I hide some blocks in predefined(?) category?

for example,
do not show "repeat (4) times" and "pause until <true>" blocks.
show others.

Thank you.

**Comment by pelikhan** [comment]
If you have something like in javascript
```
for(let i = 0; i < 4l ++i) {}
```
the javascript -> blocks decompiler will convert it into a repeat loop

**Comment by pelikhan** [comment]
we can easily hide pauseUtil in pxtarget.json

**Comment by pelikhan** [comment]
Delete this line pauseUntilBlock: {} in pxtarget.json

**Comment by pelikhan** [comment]
https://github.com/microsoft/pxt-robotis/blob/master/pxtarget.json#L92
