### ISSUE TITLE
Display "On Start" block.

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#7]
Hi,

To set up a category to display "On Start" block.
I found this..... "onStartNamespace": "loops" in "pxtarget.json"
It shows "On Start" block in "loops" category.

Can I set different categories to display "On start" block.
for example, 
"basic" category for "Robot A".
"loops" category for "Robot B".

Thank you.

**Comment by pelikhan** [comment]
I would not recommend and it is not supported at the moment.

**Comment by pelikhan** [comment]
It will be confusing in your documentation to differentiate the location of "on start"
