### ISSUE TITLE
Delete project message

### ISSUE THREAD

**Issue by kigateG** [microsoft/pxt-robotis#8]
Hi,

When I delete a project in Editor, It shows following message.
What should I do?

https://drive.google.com/file/d/1r855a0YfpovR9NKn37MYKNdtHisVBAEL/view?usp=sharing

and

https://drive.google.com/open?id=1wsJU4dAlwPeTaoBymS8hZTEem0eoQvOk

Thanks.

**Comment by pelikhan** [comment]
Deleting is not supported in localhost - which is for development only.

**Comment by pelikhan** [comment]
Note: you can copy paste screenshots into the GitHub text editor directly.

**Comment by kigateG** [comment]
Thank you for your answer.
